CREATE DATABASE shoppingmall;

USE shoppingmall;

CREATE TABLE IF NOT EXISTS User (

id BIGINT NOT NULL DEFAULT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
imageUrl VARCHAR(100) NOT NULL,
username VARCHAR(100) NOT NULL,
password VARCHAR(100) NOT NULL,
enabled BOOLEAN

);